---
title: "Bison Pool hot spring (2011, 2013)"
output: 
  rmarkdown::html_vignette:
    mathjax: null
vignette: >
  %\VignetteIndexEntry{Bison Pool hot spring (2011, 2013)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
library(knitr)
## use pngquant to reduce size of PNG images
knit_hooks$set(pngquant = hook_pngquant)
pngquant <- "--speed=1 --quality=0-25"
# in case pngquant isn't available
if (!nzchar(Sys.which("pngquant"))) pngquant <- NULL 
```

```{r HTML, include=FALSE}
## some frequently used HTML expressions
ZC <- "<i>Z</i><sub>C</sub>"
```

This vignette from the R package [JMDplots](https://github.com/jedick/JMDplots) version `r packageDescription("JMDplots")$Version` contains plots from the papers by Dick and Shock (<a href="https://doi.org/10.1371/journal.pone.0022782" title="Calculation of the relative chemical stabilities of proteins as a function of temperature and redox chemistry in a hot spring">2011</a> and <a href="https://doi.org/10.1371/journal.pone.0072395" title="A metastable equilibrium model for the relative abundances of microbial phyla in a hot spring">2013</a>).

```{r JMDplots, message = FALSE, results = "hide"}
library(JMDplots)
```

## [Measured temperature and pH](https://doi.org/10.1371/journal.pone.0022782.g005)
```{r bison1, message = FALSE, fig.align='center', out.width='100%', fig.width = 6, fig.height = 3, pngquant = pngquant}
bison1()
```
