---
title: "Yeast subcellular location (2009)"
output: 
  rmarkdown::html_vignette:
    mathjax: null
vignette: >
  %\VignetteIndexEntry{Yeast subcellular location (2009)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
library(knitr)
## use pngquant to reduce size of PNG images
knit_hooks$set(pngquant = hook_pngquant)
pngquant <- "--speed=1 --quality=0-25"
# in case pngquant isn't available
if (!nzchar(Sys.which("pngquant"))) pngquant <- NULL 
```

```{r HTML, include=FALSE}
## some frequently used HTML expressions
H2O <- "H<sub>2</sub>O"
```

This vignette contains plots from the paper by <a href="https://doi.org/10.1186/1752-0509-3-75" title="Calculation of the relative metastabilities of proteins in subcellular compartments of Saccharomyces cerevisiae">Dick (2009)</a>.
This vignette was compiled on `r Sys.Date()` with **[JMDplots](https://github.com/jedick/JMDplots)** `r packageDescription("JMDplots")$Version` **[CHNOSZ](http://chnosz.net)** `r packageDescription("CHNOSZ")$Version`.

```{r JMDplots, message = FALSE, results = "hide"}
library(JMDplots)
```

## Oxygen fugacity - activity of `r H2O` predominance diagrams (Figure 2)
```{r scsc2, message = FALSE, fig.align='center', fig.width = 7, fig.height = 7, out.width='100%', pngquant = pngquant}
scsc2()
```

## Relative equilibrium abundances of proteins as a function of oxygen fugacity (Figure 3)
```{r scsc3, message = FALSE, fig.align='center', fig.width = 7, fig.height = 5, out.width='100%', pngquant = pngquant}
scsc3()
```
